//! Provider-neutral Health State repository backed by the existing Health Vault.
use std::cmp::Ordering;
use thiserror::Error;
use crate::canonical_authorization::AuthorizationRequest;
use crate::local_health_vault::LocalHealthVaultRecord;
use crate::local_health_vault_storage::{AuthorizationContext,LocalFileVaultStore,StorageError,VaultAuthorizer,VaultKeyProvider};
const HEALTH_STATE_CONTENT_TYPE:&str="application/json";
const ALLOWED_ENTITY_TYPES:[&str;8]=["person","observation","interpretation","goal","context","intervention","response","outcome"];
#[derive(Debug,Clone,PartialEq,Eq)]pub struct AuthorizedHealthStateAccessContext{principal_ref:String,subject_ref:String,scope:String,capability_id:String,resource_type:String,resource_id:String,action:String}
impl AuthorizedHealthStateAccessContext{pub(crate)fn from_authorized_request(request:&AuthorizationRequest)->Result<Self,HealthStateRepositoryError>{let values=[&request.principal_ref,&request.subject_ref,&request.capability_id,&request.resource_type,&request.resource_id,&request.action,&request.tenant_id,&request.data_domain];if values.iter().any(|v|v.trim().is_empty()||v.chars().any(char::is_control)){return Err(HealthStateRepositoryError::AuthorizationDenied)}Ok(Self{principal_ref:request.principal_ref.clone(),subject_ref:request.subject_ref.clone(),scope:format!("{}:{}",request.tenant_id,request.data_domain),capability_id:request.capability_id.clone(),resource_type:request.resource_type.clone(),resource_id:request.resource_id.clone(),action:request.action.clone()})}pub fn principal_ref(&self)->&str{&self.principal_ref}pub fn subject_ref(&self)->&str{&self.subject_ref}pub fn scope(&self)->&str{&self.scope}pub fn capability_id(&self)->&str{&self.capability_id}pub fn resource_type(&self)->&str{&self.resource_type}pub fn resource_id(&self)->&str{&self.resource_id}pub fn action(&self)->&str{&self.action}}
#[derive(Debug,Clone,Default,PartialEq,Eq)]pub struct HealthStateQuery{pub entity_type:Option<String>,pub classification:Option<String>,pub content_type:Option<String>}
#[derive(Debug,Clone,PartialEq,Eq)]pub struct HealthStateTimelineEntry{pub record_id:String,pub subject_ref:String,pub effective_time:Option<String>,pub recorded_at:String}
#[derive(Debug,Error,PartialEq,Eq)]pub enum HealthStateRepositoryError{#[error("authorization denied")]AuthorizationDenied,#[error("health state not found")]NotFound,#[error("health state is tombstoned")]Tombstoned,#[error("repository integrity failure")]IntegrityFailure,#[error("repository storage failure")]StorageFailure,#[error("invalid Health State entity")]InvalidEntity}
impl From<StorageError> for HealthStateRepositoryError{fn from(error:StorageError)->Self{match error{StorageError::AuthorizationDenied=>Self::AuthorizationDenied,StorageError::NotFound=>Self::NotFound,StorageError::Tombstoned=>Self::Tombstoned,StorageError::IndexIntegrityFailure|StorageError::RecordIntegrityFailure=>Self::IntegrityFailure,StorageError::InvalidRecord|StorageError::KeyResolutionFailed|StorageError::Io|StorageError::Serialization|StorageError::NonceGenerationFailed=>Self::StorageFailure}}}
pub trait HealthStateRepository{fn put(&self,record:LocalHealthVaultRecord,context:&AuthorizedHealthStateAccessContext)->Result<(),HealthStateRepositoryError>;fn get(&self,record_id:&str,context:&AuthorizedHealthStateAccessContext)->Result<LocalHealthVaultRecord,HealthStateRepositoryError>;fn query(&self,context:&AuthorizedHealthStateAccessContext,query:&HealthStateQuery)->Result<Vec<LocalHealthVaultRecord>,HealthStateRepositoryError>;fn timeline(&self,context:&AuthorizedHealthStateAccessContext)->Result<Vec<HealthStateTimelineEntry>,HealthStateRepositoryError>;fn tombstone(&self,record_id:&str,context:&AuthorizedHealthStateAccessContext)->Result<(),HealthStateRepositoryError>;fn verify(&self,record_id:&str,context:&AuthorizedHealthStateAccessContext)->Result<(),HealthStateRepositoryError>}
pub struct LocalHealthStateRepository<K,A>{vault:LocalFileVaultStore<K,A>}
impl<K,A>LocalHealthStateRepository<K,A>where K:VaultKeyProvider,A:VaultAuthorizer{pub fn new(vault:LocalFileVaultStore<K,A>)->Self{Self{vault}}fn vault_context(context:&AuthorizedHealthStateAccessContext)->AuthorizationContext{AuthorizationContext{principal_ref:context.principal_ref().to_owned(),subject_ref:context.subject_ref().to_owned(),scope:context.scope().to_owned()}}fn validate_entity(record:&LocalHealthVaultRecord)->Result<(),HealthStateRepositoryError>{if !ALLOWED_ENTITY_TYPES.contains(&record.entity_type.as_str())||record.content_type!=HEALTH_STATE_CONTENT_TYPE||record.record_id.trim().is_empty()||record.subject_ref.trim().is_empty(){return Err(HealthStateRepositoryError::InvalidEntity)}Ok(())}}
impl<K,A>HealthStateRepository for LocalHealthStateRepository<K,A>where K:VaultKeyProvider,A:VaultAuthorizer{fn put(&self,record:LocalHealthVaultRecord,context:&AuthorizedHealthStateAccessContext)->Result<(),HealthStateRepositoryError>{Self::validate_entity(&record)?;if record.subject_ref!=context.subject_ref(){return Err(HealthStateRepositoryError::AuthorizationDenied)}self.vault.put(record,&Self::vault_context(context)).map_err(Into::into)}fn get(&self,record_id:&str,context:&AuthorizedHealthStateAccessContext)->Result<LocalHealthVaultRecord,HealthStateRepositoryError>{let record=self.vault.get(record_id,&Self::vault_context(context)).map_err(HealthStateRepositoryError::from)?;Self::validate_entity(&record)?;if record.subject_ref!=context.subject_ref(){return Err(HealthStateRepositoryError::AuthorizationDenied)}Ok(record)}fn query(&self,context:&AuthorizedHealthStateAccessContext,query:&HealthStateQuery)->Result<Vec<LocalHealthVaultRecord>,HealthStateRepositoryError>{let entries=self.vault.list(&Self::vault_context(context)).map_err(HealthStateRepositoryError::from)?;let mut records=Vec::new();for entry in entries{if !ALLOWED_ENTITY_TYPES.contains(&entry.entity_type.as_str())||query.entity_type.as_ref().is_some_and(|v|entry.entity_type!=*v)||query.classification.as_ref().is_some_and(|v|entry.classification!=*v)||query.content_type.as_ref().is_some_and(|v|entry.content_type!=*v){continue}records.push(self.get(&entry.record_id,context)?)}Ok(records)}fn timeline(&self,context:&AuthorizedHealthStateAccessContext)->Result<Vec<HealthStateTimelineEntry>,HealthStateRepositoryError>{let entries=self.vault.list(&Self::vault_context(context)).map_err(HealthStateRepositoryError::from)?;let mut timeline=entries.into_iter().filter(|e|ALLOWED_ENTITY_TYPES.contains(&e.entity_type.as_str())).map(|e|HealthStateTimelineEntry{record_id:e.record_id,subject_ref:e.subject_ref,effective_time:None,recorded_at:e.created_at}).collect::<Vec<_>>();timeline.sort_by(|l,r|match(&l.effective_time,&r.effective_time){(Some(a),Some(b))=>match a.cmp(b){Ordering::Equal=>l.recorded_at.cmp(&r.recorded_at),o=>o},(Some(_),None)=>Ordering::Less,(None,Some(_))=>Ordering::Greater,(None,None)=>l.recorded_at.cmp(&r.recorded_at)}.then_with(||l.record_id.cmp(&r.record_id)));Ok(timeline)}fn tombstone(&self,record_id:&str,context:&AuthorizedHealthStateAccessContext)->Result<(),HealthStateRepositoryError>{self.vault.tombstone(record_id,&Self::vault_context(context)).map_err(Into::into)}fn verify(&self,record_id:&str,context:&AuthorizedHealthStateAccessContext)->Result<(),HealthStateRepositoryError>{self.vault.verify(record_id,&Self::vault_context(context)).map_err(Into::into)}}
#[cfg(test)]mod tests{use super::*;use crate::canonical_authorization::AuthorizationDecision;#[test]fn delegated_context_preserves_actor_and_subject(){let request=AuthorizationRequest{principal_ref:"clinician-1".into(),subject_ref:"patient-1".into(),capability_id:"health.state.read".into(),resource_type:"health_state".into(),resource_id:"record-1".into(),action:"read".into(),tenant_id:"tenant-1".into(),data_domain:"personal_health".into()};let context=AuthorizedHealthStateAccessContext::from_authorized_request(&request).unwrap();assert_eq!(context.principal_ref(),"clinician-1");assert_eq!(context.subject_ref(),"patient-1");assert_ne!(context.principal_ref(),context.subject_ref());assert_eq!(AuthorizationDecision::Allow.allows_protected_execution(),true)}}
