//! Provider-neutral longitudinal observation and timeline contract.
use std::cmp::Ordering;use thiserror::Error;use crate::canonical_authorization::AuthorizationRequest;
#[derive(Debug,Clone,PartialEq,Eq)]pub struct AuthorizedObservationAccessContext{principal_ref:String,subject_ref:String,scope:String,capability_id:String,resource_type:String,resource_id:String,action:String}
impl AuthorizedObservationAccessContext{pub(crate)fn from_authorized_request(request:&AuthorizationRequest)->Result<Self,ObservationRepositoryError>{if[&request.principal_ref,&request.subject_ref,&request.capability_id,&request.resource_type,&request.resource_id,&request.action,&request.tenant_id,&request.data_domain].iter().any(|v|v.trim().is_empty()||v.chars().any(char::is_control)){return Err(ObservationRepositoryError::AuthorizationDenied)}Ok(Self{principal_ref:request.principal_ref.clone(),subject_ref:request.subject_ref.clone(),scope:format!("{}:{}",request.tenant_id,request.data_domain),capability_id:request.capability_id.clone(),resource_type:request.resource_type.clone(),resource_id:request.resource_id.clone(),action:request.action.clone()})}pub fn principal_ref(&self)->&str{&self.principal_ref}pub fn subject_ref(&self)->&str{&self.subject_ref}pub fn scope(&self)->&str{&self.scope}pub fn capability_id(&self)->&str{&self.capability_id}pub fn resource_type(&self)->&str{&self.resource_type}pub fn resource_id(&self)->&str{&self.resource_id}pub fn action(&self)->&str{&self.action}}
#[derive(Debug,Clone,PartialEq,Eq)]pub struct ObservationQuery{pub concept:Option<String>,pub status:Option<String>,pub classification:Option<String>}
#[derive(Debug,Clone,PartialEq,Eq)]pub struct ObservationTimelineEntry{pub observation_id:String,pub subject_ref:String,pub observed_at:Option<String>,pub recorded_at:String}
#[derive(Debug,Error,PartialEq,Eq)]pub enum ObservationRepositoryError{#[error("authorization denied")]AuthorizationDenied,#[error("observation not found")]NotFound,#[error("observation is tombstoned")]Tombstoned,#[error("repository integrity failure")]IntegrityFailure,#[error("repository storage failure")]StorageFailure,#[error("invalid observation")]InvalidObservation}
pub trait LongitudinalObservationRepository{type Observation;fn put_reference(&self,observation_id:&str,context:&AuthorizedObservationAccessContext)->Result<(),ObservationRepositoryError>;fn get(&self,observation_id:&str,context:&AuthorizedObservationAccessContext)->Result<Self::Observation,ObservationRepositoryError>;fn query(&self,context:&AuthorizedObservationAccessContext,query:&ObservationQuery)->Result<Vec<Self::Observation>,ObservationRepositoryError>;fn timeline(&self,context:&AuthorizedObservationAccessContext)->Result<Vec<ObservationTimelineEntry>,ObservationRepositoryError>;fn tombstone(&self,observation_id:&str,context:&AuthorizedObservationAccessContext)->Result<(),ObservationRepositoryError>;fn verify(&self,observation_id:&str,context:&AuthorizedObservationAccessContext)->Result<(),ObservationRepositoryError>}
pub fn sort_timeline(entries:&mut[ObservationTimelineEntry]){entries.sort_by(|l,r|match(&l.observed_at,&r.observed_at){(Some(a),Some(b))=>match a.cmp(b){Ordering::Equal=>l.recorded_at.cmp(&r.recorded_at),o=>o},(Some(_),None)=>Ordering::Less,(None,Some(_))=>Ordering::Greater,(None,None)=>l.recorded_at.cmp(&r.recorded_at)}.then_with(||l.observation_id.cmp(&r.observation_id)))}
#[cfg(test)]mod tests{use super::*;fn request()->AuthorizationRequest{AuthorizationRequest{principal_ref:"person-1".into(),subject_ref:"person-1".into(),capability_id:"health.read".into(),resource_type:"health_record".into(),resource_id:"record-1".into(),action:"read".into(),tenant_id:"tenant-1".into(),data_domain:"personal_health".into()}}#[test]fn delegated_context_preserves_actor_and_subject(){let mut r=request();r.principal_ref="clinician-1".into();r.subject_ref="patient-1".into();let c=AuthorizedObservationAccessContext::from_authorized_request(&r).unwrap();assert_eq!(c.principal_ref(),"clinician-1");assert_eq!(c.subject_ref(),"patient-1");assert_ne!(c.principal_ref(),c.subject_ref())}#[test]fn malformed_request_cannot_create_context(){let mut r=request();r.action.clear();assert_eq!(AuthorizedObservationAccessContext::from_authorized_request(&r),Err(ObservationRepositoryError::AuthorizationDenied))}#[test]fn timeline_keeps_unknown_time_unknown(){let mut e=vec![ObservationTimelineEntry{observation_id:"b".into(),subject_ref:"person-1".into(),observed_at:None,recorded_at:"2026-09-01T00:00:00Z".into()},ObservationTimelineEntry{observation_id:"a".into(),subject_ref:"person-1".into(),observed_at:Some("2026-08-01T00:00:00Z".into()),recorded_at:"2026-09-10T00:00:00Z".into()}];sort_timeline(&mut e);assert_eq!(e[0].observation_id,"a");assert_eq!(e[1].observed_at,None)}}
